# Here are the settings that are common to all environments
common: &default_settings
  license_key: <%= ENV["NEWRELIC_LICENSE_KEY"] %>

  app_name: Flashcards2

  monitor_mode: true
  developer_mode: false

  log_level: info

  browser_monitoring:
      auto_instrument: true

  audit_log:
    enabled: false

  capture_params: false

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"

development:
  <<: *default_settings
  # Turn on communication to New Relic service in development mode
  monitor_mode: true
  app_name: Flashcards2 (Development)
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  monitor_mode: true
  app_name: Flashcards2 (Staging)
