development:
  secret_key_base: 6545169f7275d2e5a1a7b58677135ed1cfe4bcdc59d87907f5258c263e8c270376c357ac62f7a68eb352b3bbcac3120271cf3207cf836f9c3f1646af63a93aef
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>
test:
  secret_key_base: d1632de87a7808a14d48f0115dc19ebd194e9589bf452db7b3dbfd7936fcc1ac19e8ee9196fb163242b88acb3b2843b594297c5dfbd53947b4566ec010d4f7ab
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>